[bbooing] Feature/review
wecode-bootcamp-korea/31-2nd-bbooing-backend pull request #14
Opened 2022-04-20 05:26 UTC by gleehave

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 리뷰를 업로드할 수 있다. (댓글, 이미지)
- 이미지는 AWS S3를 활용하여 저장한다.
- 리뷰를 삭제할 경우, AWS S3 이미지도 같이 삭제한다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. POST 메서드를 통해서, 댓글(text type)은 DB에 저장하고, 첨부된 이미지는 s3에 업로드 합니다.
2. S3 connect의 문제로 저장되지 않을경우, transaction.atomic()으로 rollback 할 수 있도록 구현.
3. review를 지울 경우, review_id를 찾아 삭제하고, s3에 저장된 이미지 이름을 parsing해서 s3에서 삭제처리
4. S3 관련 로직은 core/s3.py 에 작성, aws의 key값들과 bucket, region은 settings에 기입

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- boto3 를 이용해서 aws s3와 통신을 함. 이때, S3 client를 생성자(__init__)로 생성하는 부분만 관리하고, 중간에 FileUpload, FileDelete 클래스를 두어, 중간 controller역할을 담당할 수 있도록 함.
- 이렇게 작업했을 때, 테스트 코드에서 확인하기 편리해짐. 또한, 이 외에 S3기능을 추가로 사용할 때에도 확장성이 좋아짐.
- URL을 만들 때, '/<int:lecture_id>', ~~as_view().   '/<int:review_id>', ~~as_view().  이렇게 있을 때, TypeError가 발생함. URL 작업 시에 반드시 유의할 점임.

<br />

## :: 기타 질문 및 특이 사항
- aws s3 테스트코드에서 도움이 필요합니다.

2022-04-20 09:01 UTC, lordmyshepherd requested changes

2022-04-20 09:01 UTC, lordmyshepherd commented on reviews/tests.py
> +# class S3ClientTest(TestCase):
```python
class ReviewView(TestCase):
    def setUp(self):
        pass

    def tearDown(self):
        pass

    @patch('reviews.views.FileUpload.upload')
    def test_test(self, mocked_aws):
        client = Client()

        access_token = jwt.encode({
            'user_id': 1,
            'exp': datetime.utcnow() + timedelta(days=1)
        }, settings.SECRET_KEY, settings.ALGORITHM)

        headers = {'HTTP_Authorization': access_token}
    
        # file objects를 만들어야 합니다. BytesIO(), Django SimpleFileUpload()
        image = SimpleFileObjects(type='png')
           
        data = {
            "content" : "sss",
            "review_images" : [image1, image2]
        }

        mocked_aws.return_value = f'https://{settings.bucket_name}.s3.{settings.region}.amazonaws.com/test1.png'

        response = client.post('/reviews/lectures/1', data = data, format='multipart', **headers)


        self.assertEqual(response, 200)
```

2022-04-20 12:26 UTC, gleehave commented on reviews/tests.py
> +# class S3ClientTest(TestCase):
병민님! 감사합니다! 
병민님 주신 피드백 반영해서 다시 push 올렸습니다... (병민님이 없었으면 테스트코드 못돌려봤을 것 같아요.. ㅎ... )

2022-04-20 12:28 UTC, gleehave commented on reviews/tests.py
> +# class S3ClientTest(TestCase):
@bigfanoftim 
호준님! 감사합니다!
테스트코드 작성하느라 너무 지쳐있었는데.. 
호준님이 알려주신덕분에 여기까지 올릴 수 있었습니다.. ㅠㅠㅠㅠ

2022-04-21 01:39 UTC, jamessoun93 requested changes

2022-04-21 01:39 UTC, jamessoun93 commented on core/s3.py
> +        return self.s3client.delete(bucket_name, image_name)
upload와 delete를 각각 담당하는 wrapper class를 따로 만들어주신 이유가 있을가요?

2022-04-21 01:39 UTC, jamessoun93 commented on core/s3.py
> +    def __init__(self, accessKey, secretKey, bucketName, region):
snake_case로 통일해주세요.

2022-04-21 01:39 UTC, jamessoun93 commented on core/s3.py
> +        self.region      = region
- 생성자에 `boto3.client('s3', ...)`를 직접 노출시키게 되면 추후 Naver Cloud Platform으로 바뀐다던지 추가를 해야할 때 아예 새로운 클래스를 만들거나 이 모든 부분이 수정되어야 합니다. 
- 해당 클래스가 제공하는 인터페이스는 그대로 둔채 내부 구현사항만 변경될 수 있게끔 설계를 해주시는게 좋습니다.

예시
```python
import boto3
import uuid

class FileUploader:
    def __init__(self, client, config):
        self.client = client
        self.config = config

    def upload(self, file):
        try: 
            file_id    = str(uuid.uuid4())
            extra_args = {'ContentType' : file.content_type}

            self.client.upload_fileobj(
                file,
                config.bucket_name,
                file_id,
                ExtraArgs = extra_args
            )
            return f'https://{config.bucket_name}.s3.ap-northeast-2.amazonaws.com/{file_id}'
        except:
            return None

    def delete(self, file_name):
        return self.client.delete_object(bucket=config.bucket_name, Key=f'{file_name}')

class FileHandler:
    def __init__(self, client):
        self.client = client
    
    def upload(self, file):
        return self.client.upload(file)

    def delete(self, file_name):
        return self.client.delete(file_name)

...

file_uploader = FileUploader(boto3.client('s3'), config)
file_handler = FileHandler(file_uploader)
file_handler.upload(file)

file_uploader = FileUploader(naver_cloud.client('cdn'), config)
file_handler = FileHandler(file_uploader)
file_handler.upload(file)
```

- 이렇게 하면 나중에 Naver Cloud로 변경을 원할 시 다음 처럼 FileHandler 클래스는 수정할 필요가 없습니다.
- 단, 해당하는 클라우드 플랫폼에 맞는 구체적인 구현사항을 담은 FileUploader 클래스는 해당하는 로직에 맞게 수정해주셔야 합니다.

2022-04-21 02:11 UTC, gleehave commented on core/s3.py
> +        return self.s3client.delete(bucket_name, image_name)
AWS에서 제공하는 upload_fileobj 함수와 delete_object 함수를 사용하기 전에 중간 class를 두어서 controller(혹은 adapter) 처럼 사용하려고 작성했습니다.

더 나아가서, AWS 외에 다른 서비스를 사용할 때에도 좀 더 확장성 있게 사용할 수 있다고 판단되서 wrapper class를 작성하였습니다.

2022-04-21 02:12 UTC, gleehave commented on core/s3.py
> +    def __init__(self, accessKey, secretKey, bucketName, region):
넵!
S3Client -> S3_Client 로 변경하겠습니다!

2022-04-21 05:00 UTC, gleehave commented on core/s3.py
> +        self.region      = region
작업해서 push 올렸습니다... 

@jamessoun93 
"단, 해당하는 클라우드 플랫폼에 맞는 구체적인 구현사항을 담은 FileUploader 클래스는 해당하는 로직에 맞게 수정해주셔야 합니다."
이 부분 피드백에 대해서 한번 더 알려주시면 감사하겠습니다.. ㅠ

2022-04-21 09:10 UTC, jamessoun93 commented on core/s3.py
> +    def __init__(self, accessKey, secretKey, bucketName, region):
클래스명을 말씀드린게 아니고 init 메서드의 인자부분을 말씀드린거였어요~

2022-04-21 09:59 UTC, gleehave commented
<img width="573" alt="스크린샷 2022-04-21 오후 6 58 45" src="https://user-images.githubusercontent.com/91510831/164430794-bb3be921-abf0-4b11-a71a-5a6bc57ce823.png">

2022-04-21 16:52 UTC, merged