[류미류][modify] 필터/검색 기능 구현
wecode-bootcamp-korea/31-2nd-bbooing-backend pull request #15
Opened 2022-04-20 06:39 UTC by mquat

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 제품(강의) 필터/검색 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 제품 검색 기능 
- <img width="635" alt="검색기능_결과 예시" src="https://user-images.githubusercontent.com/97735091/164165972-f6bf6e0a-e1af-4694-9a87-d0a0f1775978.png">

- 제품 다중필터 기능
<img width="797" alt="다중필터_결과 예시" src="https://user-images.githubusercontent.com/97735091/164165970-37e4f17a-fd31-433a-83f7-58db714e95b5.png">

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-04-20 08:43 UTC, lordmyshepherd requested changes

2022-04-20 08:43 UTC, lordmyshepherd commented on lectures/tests.py
> +        Type.objects.create(id = 2, type = 'VOD')
`bulk_create()` 사용해서 구현해주세요~

2022-04-20 08:43 UTC, lordmyshepherd commented on lectures/tests.py
> +        self.assertEqual(response.json()['result'][0]['title'], '기초부터 배우는 초단간 5분 드로잉')
title 하나만 비교하게 되면 다른 컬럼에 변경사항이 있을 때, 잡아내기 어렵습니다.
반드시 full json 데이터를 비교해주세요.

2022-04-20 08:43 UTC, lordmyshepherd commented on lectures/views.py
> +            condition &= Q(schedulelecture__schedule__schedule__in = schedules)
```python
filter_set = {
    "title" : "title__icontains",
    "regions" : "regionlecture__region__region__in",
    "schedules" : "schedulelecture__schedule__schedule__in",
}

q = {filter_set[key] : value for key, value in request.GET.items()}

lectures = Lecture.objects....filter(**q)
```

2022-04-20 08:43 UTC, lordmyshepherd commented on lectures/views.py
> +        schedules   = request.GET.getlist('schedules', None)
```suggestion
```

2022-04-20 08:43 UTC, lordmyshepherd commented on lectures/views.py
> +            'likes'     : lecture.like_set.aggregate(likes = Count('lectures_id'))['likes'],
앞 PR에서 드린 피드백과 동일합니다.

2022-04-20 08:43 UTC, lordmyshepherd commented on lectures/views.py
> +            'types'     : lecture.types.get().id,
여기도 마찬가지. 사실은 DB 구조를 변경하셔야 합니다. 추후에 리펙토링해주세요.

2022-04-20 08:43 UTC, lordmyshepherd commented on lectures/views.py
> +            'likes'     : lecture.like_set.aggregate(likes = Count('lectures_id'))['likes'],
피드백 반영 필요

2022-04-20 08:43 UTC, lordmyshepherd commented on lectures/views.py
> +            condition &= Q(schedulelecture__schedule__schedule__in = schedules)
추후에 반영해주세요.

2022-04-21 03:06 UTC, mquat commented
안녕하세요 병민님, 피드백 반영 완료 했습니다. 확인 부탁 드립니다!

2022-04-21 05:54 UTC, merged