[bbooing] 상세페이지
wecode-bootcamp-korea/31-2nd-bbooing-backend pull request #5
Opened 2022-04-15 01:20 UTC by gleehave

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 1개의 Lecture에 대한 상세페이지 접속 시, Lecture에 대한 내용 조회

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. Lecture 페이지 작성
    - 상세페이지 내용 조회.
<img width="904" alt="스크린샷 2022-04-15 오전 10 14 45" src="https://user-images.githubusercontent.com/91510831/163502406-0dde7633-f7ec-41a9-9c37-c1b9cb55217c.png">
2. 테스트 코드 작성
    - GET 메서드 디테일 페이지 Unittest 수행.
    - 조회된 데이터와 Lecture.DoesNotExist 테스트 수행
<img width="582" alt="스크린샷 2022-04-15 오전 10 15 31" src="https://user-images.githubusercontent.com/91510831/163502459-09bd0106-d28b-4e41-8b6d-c89efb4cd4c1.png">
3. token 
    - token 유효성 검사 데코레이터 작성
    - 해당 코드는 상세페이지의 review 이미지 업로드, 댓글 작성에 사용

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- status 코드와 에러에 대한 유닛테스트를 수행함. 이때, Test DB의 존재가 필요함을 생각하게 됨.
- lecture와 review의 기능을 명확하게 분리해서 바라볼 수 있는 계기가 되었음.

<br />

## :: 기타 질문 및 특이 사항
- 특이사항 없습니다.

2022-04-15 02:34 UTC, bigfanoftim requested changes
강호님!! PR 너무 잘 작성해주셨는데 한가지 아쉬운점이 있습니다!!

`token_validate`는 해당 PR과 전혀 상관없는 코드입니다. 따로 PR 만들어서 올려주시고 곧바로 머지받아주세요!

2022-04-15 03:33 UTC, gleehave commented
@bigfanoftim 

호준님! 내용 확인했습니다.
현재, feature/token_decorator 라는 브랜치에서 새로운 PR 올렸습니다!

2022-04-15 08:58 UTC, jamessoun93 requested changes

2022-04-15 08:58 UTC, jamessoun93 commented on lectures/views.py
> +                }for review in lecture.review_set.all()]
오늘 배우신 것 써보시면 좋을 것 같은데요?!

2022-04-15 09:33 UTC, gleehave commented on lectures/views.py
> +                }for review in lecture.review_set.all()]
넵!
ORM 최적화 한번 적용해 보겠습니다!

2022-04-16 13:25 UTC, jamessoun93 approved these changes

2022-04-16 13:25 UTC, merged