[류미류][add] 메인페이지 view/test 작성 완료
wecode-bootcamp-korea/31-2nd-bbooing-backend pull request #8
Opened 2022-04-18 03:09 UTC by mquat

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메인 페이지 views 
- 메인 페이지 test (test code)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 메인 페이지 슬라이드를 위한 강의 list (GET)
- test code 
- 아래는 위 2개 내용 test 캡처본입니다 
![스크린샷 2022-04-18 오전 11 21 07](https://user-images.githubusercontent.com/97735091/163748339-a64f728a-a774-41de-b048-0a02ea4f65f6.png)
![스크린샷 2022-04-18 오전 11 25 59](https://user-images.githubusercontent.com/97735091/163748345-4d991351-8fa9-4f51-980d-648217383cac.png)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-04-18 08:08 UTC, jamessoun93 submitted a review, later dismissed

2022-04-18 08:08 UTC, jamessoun93 commented on core/utils.py
> +            payload      = jwt.decode(access_token, settings.SECRET_KEY, algorithms=settings.ALGORITHM)
요청에 Authorization 헤더가 존재하지 않거나 잘못되었을때 어떻게 되는지 확인해보셨을까요!?

2022-04-18 10:03 UTC, jamessoun93 requested changes

2022-04-18 10:03 UTC, jamessoun93 commented on core/utils.py
> +def login_decortor(func):
```suggestion
def login_decorator(func):
```

2022-04-20 05:26 UTC, mquat commented
메인 view 수정했습니다, 확인 부탁 드립니다!

2022-04-20 08:02 UTC, lordmyshepherd commented
lectures 코드만 올라올 수 있도록 나머지 코드는 지워주세요-!

2022-04-20 08:32 UTC, lordmyshepherd requested changes

2022-04-20 08:32 UTC, lordmyshepherd commented on lectures/tests.py
> +        self.assertEqual(response.json()['total_list'][0]['title'], '베인앤컴퍼니 출신의 논리적으로 일하는 법')
결과 전체를 비교해주세요~

2022-04-20 08:32 UTC, lordmyshepherd commented on lectures/views.py
> +        introduction = ['당장 들어야 할 오프라인 클래스', '뿌잉 VOD, 같이하면 더 쉬우니까', '지금! 뜨고 있는 전자책 클래스']
```python
class Lecture(models.Model):
    introductions = [
        '당장 들어야 할 오프라인 클래스', 
        '뿌잉 VOD, 같이하면 더 쉬우니까', 
        '지금! 뜨고 있는 전자책 클래스'
    ]

    type_id = models...
    
    @property
    def introduction(self):
        return introductions[self.type.id - 1]
```

2022-04-20 08:32 UTC, lordmyshepherd commented on lectures/views.py
> +            'introduction' : introduction[type.id-1],
```suggestion
            'introduction' : lecture.introduction,
```

2022-04-20 08:32 UTC, lordmyshepherd commented on lectures/views.py
> +        introduction = ['당장 들어야 할 오프라인 클래스', '뿌잉 VOD, 같이하면 더 쉬우니까', '지금! 뜨고 있는 전자책 클래스']
```suggestion
```

2022-04-20 08:32 UTC, lordmyshepherd commented on lectures/views.py
> +        lectures = Lecture.objects.select_related('category')\
```suggestion
        lectures = Lecture.objects.select_related('category').annotate(like_count=Count('like__id').
```

2022-04-20 08:32 UTC, lordmyshepherd commented on lectures/views.py
> +                'likes'     : lecture.like_set.aggregate(likes = Count('lectures_id'))['likes'],
```suggestion
                'likes'     : lecture.like_count,
```

2022-04-20 08:32 UTC, lordmyshepherd commented on lectures/views.py
> +            } for lecture in lectures.filter(Q(typelecture__type_id = type.id))]
```suggestion
            } for lecture in lectures.filter(typelecture__type_id = type.id)]
```

2022-04-20 08:32 UTC, lordmyshepherd commented on lectures/views.py
> +        return JsonResponse({'total_list' : result}, status = 200)
```python
    def get(self, request):
        lectures = Lecture.objects.select_related('category').annotate(like_count=Count('likes__id'))\
            .prefetch_related('regions', 'schedules','lectureimage_set')
        
        result = [{
            'type_id' : type.id,
            'introduction' : lecture.introduction,
            'lecture' : [{
                'lecture_id': lecture.id,
                'title'     : lecture.title,
                'category'  : lecture.category.name,
                'regions'   : [{"id" : region.id, "name" : region.name} for region in lecture.regions.all()],
                'schedules' : [{"id" : schedule.id, "name" : schedule.name for schedule in lecture.schedules.all()], 
                'price'     : lecture.price,
                'likes'     : lecture.like_count,
                'images'    : [image.image_url for image in lecture.lectureimage_set.all()]
            } for lecture in lectures
        ]
        
        return JsonResponse({'lectures' : lectures}, status = 200)
```

2022-04-20 08:32 UTC, lordmyshepherd commented on lectures/views.py
> +        introduction = ['당장 들어야 할 오프라인 클래스', '뿌잉 VOD, 같이하면 더 쉬우니까', '지금! 뜨고 있는 전자책 클래스']
피드백 반영 필요!

2022-04-20 08:32 UTC, lordmyshepherd commented on lectures/views.py
> +        lectures = Lecture.objects.select_related('category')\
피드백 반영 필요!

2022-04-20 08:32 UTC, lordmyshepherd commented on lectures/views.py
> +            'introduction' : introduction[type.id-1],
피드백 반영 필요!

2022-04-20 08:32 UTC, lordmyshepherd commented on lectures/views.py
> +            } for lecture in lectures.filter(Q(typelecture__type_id = type.id))]
피드백 반영 필요!

2022-04-20 08:32 UTC, lordmyshepherd commented on lectures/views.py
> +        return JsonResponse({'total_list' : result}, status = 200)
추후 리펙터링 해주세요~

2022-04-20 19:19 UTC, mquat commented
병민님, 수정사항 반영해서 올렸는데 문제는... lectures 외의 내용들이 계속 보존 or 추가되고 있는데 이들을 어떻게 제거해야 할지 잘 모르겠습니다 ㅜ... 한번 확인 부탁 드립니다.

2022-04-21 01:11 UTC, jamessoun93 commented
제가 이따가 봐드릴게요!

2022-04-21 07:16 UTC, merged